version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
volumes:
  redis_data:

